# Importando as bibliotecas

In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np

# Carregando o conjunto de dados

In [4]:
df = pd.read_table('/content/drive/MyDrive/dados.txt', header=None)
df

       0     1  2
0   0.77 -1.14  0
1  -0.33  1.44  0
2   0.91 -3.07  0
3  -0.37 -1.91  0
4  -1.84 -1.13  0
..   ...   ... ..
95  0.71  2.27  1
96  1.96  0.83  1
97  2.52  1.83  1
98  2.77  2.82  1
99  4.16  3.34  1

[100 rows x 3 columns]

# Separando as variáveis

In [9]:
X = df[[0, 1]]

In [11]:
X.head()

      0     1
0  0.77 -1.14
1 -0.33  1.44
2  0.91 -3.07
3 -0.37 -1.91
4 -1.84 -1.13

In [13]:
y = df[[2]]
y.head()

   2
0  0
1  0
2  0
3  0
4  0

In [15]:
X.shape

(100, 2)

In [16]:
y.shape

(100, 1)

# Separando os dados para treino e teste

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=123)

In [19]:
print('X_train_Shape',X_train.shape)
print('y_train_Shape',y_train.shape)
print('X_test_Shape',X_test.shape)
print('y_test_Shape',y_test.shape)

X_train_Shape (60, 2)
y_train_Shape (60, 1)
X_test_Shape (40, 2)
y_test_Shape (40, 1)

# Normalização dos dados

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [22]:
print('X_train mean', np.mean(X_train))
print('X_train standard deviation', np.std(X_train))

X_train mean 2.0354088784794535e-17
X_train standard deviation 1.0

# Construindo o modelo

In [39]:
model = tf.keras.Sequential()
model.add(tf.keras.Input(shape=(2,)))
model.add(tf.keras.layers.Dense(1, kernel_initializer='zeros'))
model.add(tf.keras.layers.Activation('sigmoid'))

model.compile(loss='binary_crossentropy', optimizer= 'sgd', metrics=['accuracy'])

In [40]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_2 (Dense)             (None, 1)                 3

 activation_2 (Activation)   (None, 1)                 0

=================================================================
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________

# Fazendo o treinamento do modelo

In [41]:
model.fit(X_train, y_train, epochs=10, batch_size=5, verbose=1)

Epoch 1/10
12/12 [==============================] - 0s 1ms/step - loss: 0.6743 - accuracy: 0.9500
Epoch 2/10
12/12 [==============================] - 0s 1ms/step - loss: 0.6351 - accuracy: 0.9667
Epoch 3/10
12/12 [==============================] - 0s 2ms/step - loss: 0.5999 - accuracy: 0.9667
Epoch 4/10
12/12 [==============================] - 0s 1ms/step - loss: 0.5679 - accuracy: 0.9667
Epoch 5/10
12/12 [==============================] - 0s 1ms/step - loss: 0.5390 - accuracy: 0.9667
Epoch 6/10
12/12 [==============================] - 0s 1ms/step - loss: 0.5129 - accuracy: 0.9667
Epoch 7/10
12/12 [==============================] - 0s 1ms/step - loss: 0.4892 - accuracy: 0.9667
Epoch 8/10
12/12 [==============================] - 0s 1ms/step - loss: 0.4676 - accuracy: 0.9667
Epoch 9/10
12/12 [==============================] - 0s 2ms/step - loss: 0.4479 - accuracy: 0.9667
Epoch 10/10
12/12 [==============================] - 0s 2ms/step - loss: 0.4298 - accuracy: 0.9667

# Avaliação do modelo

In [42]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 7ms/step - loss: 0.4396 - accuracy: 0.9750

In [46]:
y_test_pred = model.predict(X_test)
y_test_pred = np.reshape(y_test_pred, -1)
print(y_test_pred)

[0.40222088 0.60212743 0.62987053 0.34887463 0.7008927  0.45575047
 0.4216835  0.66649115 0.68658215 0.34569764 0.30352998 0.6363814
 0.5795463  0.615667   0.23711854 0.531417   0.61409706 0.25441757
 0.6873685  0.7093333  0.37706736 0.58303064 0.29209113 0.27622145
 0.20621806 0.52272576 0.69420534 0.29930064 0.5971537  0.27235734
 0.3426044  0.5729216  0.26838696 0.6169261  0.70426285 0.63148224
 0.6033577  0.65964115 0.61085904 0.3740356 ]

In [47]:
y_test_pred = np.where(y_test_pred>0.5, 1, 0)
print(y_test_pred)

[0 1 1 0 1 0 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 1 1 1
 1 1 0]

In [48]:
print(np.array(y_test).T)

[[0 1 1 0 1 0 0 1 1 0 0 1 1 1 0 0 1 0 1 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 1 1
  1 1 1 0]]

In [49]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_test_pred)

0.975